In [1]:
import torch
print(torch.__version__)

2.0.1+cpu


## Introduction to tensors

### creating tensors

In [2]:
# Scalars

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
## Matrix

MATRIX = torch.Tensor([[7,8], 
                        [9, 10]])
MATRIX

tensor([[ 7.,  8.],
        [ 9., 10.]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7., 8.])

In [11]:
MATRIX[1]

tensor([ 9., 10.])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
## Tensor

TENSOR = torch.tensor([[[1,2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random tensors 

In [16]:
# Create a random tensor in Pytorch

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3557, 0.8904, 0.4845, 0.6634],
        [0.4343, 0.5399, 0.1657, 0.4485],
        [0.6841, 0.5133, 0.0370, 0.7831]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 4])

In [19]:
# Random tensor to similar shape as image tensor

random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [20]:
# Tensor of all zeros

zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Tensor of all ones

ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Creating a range of tensors and tensors-like

In [23]:
# Creating a range

one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor data type

In [26]:
# float32 tensor

float32_tensor = torch.tensor([3., 6., 9.], 
                              dtype=None,
                              device=None,
                              requires_grad=False)
float32_tensor

tensor([3., 6., 9.])

## Manipulating tensors

In [27]:
# Create a tensor

tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [28]:
# Multiply

tensor*10

tensor([10, 20, 30])

In [29]:
# Subtract

tensor-10

tensor([-9, -8, -7])