In [1]:
import torch
print(torch.__version__)

2.0.1+cpu


## Introduction to tensors

### creating tensors

In [2]:
# Scalars

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [7]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [14]:
## Matrix

MATRIX = torch.Tensor([[7,8], 
                        [9, 10]])
MATRIX

tensor([[ 7.,  8.],
        [ 9., 10.]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[0]

tensor([7., 8.])

In [17]:
MATRIX[1]

tensor([ 9., 10.])

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
## Tensor

TENSOR = torch.tensor([[[1,2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [24]:
TENSOR.ndim

3

In [25]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random tensors 

# Create a random tensor in Pytorch